### ISSUE TITLE
Survival data sets

### ISSUE THREAD

**Issue by therneau** [higgi13425/medicaldata#1]
The survival package has a large collection of data sets.   Do you think there would be a benefit from linking them here as well?
Terry Therneau
therneau@mayo.edu

**Comment by higgi13425** [comment]
It sounds like several people would like survival datasets. 
Are there some that are
- deidentified
- permission to share is confirmed
- there is a published manuscript
- there is a reasonably good codebook/portion of a codebook for?

I think people would like a few survival datasets, possibly famous ones, included in {medicaldata}.

thanks for any proposals!

Peter

**Comment by higgi13425** [comment]
Will start to incorporate - folks at R/Med were clearly interested. Will start with dev version on GitHub (0.3.0), and will eventually be in CRAN version (likely next submission Feb 2022).
Thanks, 
Peter
