### ISSUE TITLE
indo_rct_codebook typo

### ISSUE THREAD

**Issue by daszlosek** [higgi13425/medicaldata#2]
```indo_rct_codebook.html``` states a different column name (```bsphinct```) than the ```indo_rct``` dataset (```bsphinc```).

[Codebook source](https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/codebooks/indo_rct_codebook.html)

**Comment by higgi13425** [comment]
Thanks, @daszlosek  - now fixed on website and in dev version on GitHub (v 0.3.0). Great catch!
