### ISSUE TITLE
Add study design to data set description table

### ISSUE THREAD

**Issue by ddsjoberg** [higgi13425/medicaldata#4]
hey hey @higgi13425 !

I've used medicaldata a couple of times, and it is wonderful! thank you!

Each time i go searching for a dataset, I have a specific type of study design that I need. I think it would be helpful for the users to add the study design to the table listing the data sets available.

![image](https://user-images.githubusercontent.com/26774684/165751054-c699bd81-e1bb-4779-803b-cab3a458655d.png)

**Comment by higgi13425** [comment]
Nice idea - will implement this weekend.

**Comment by higgi13425** [comment]
Actually easier than I thought - done!

**Comment by ddsjoberg** [comment]
Thanks @higgi13425 !!!
