### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by avehtari** [higgi13425/medicaldata#5]
The package looks very useful. While reading the doc I noticed that there some broken links in
the table in page https://higgi13425.github.io/medicaldata/
- "diabetes (dev)" row has links to theoph_desc and theoph_codebook (repeating the links from the previous row)
- "thiomon (dev)" and "abm (dev)" rows have links that give "404: not found"

**Comment by higgi13425** [comment]
Thanks for catching these - left as placeholders that I apparently did not get back to. the abm dataset now has desc and codebook. Working on diabetes and thiomon next

**Comment by higgi13425** [comment]
Diabetes description and codebook completed

**Comment by higgi13425** [comment]
Thiomon desc and codebook now completed

**Comment by higgi13425** [comment]
On a related note, if you have an example of using any of these datasets in Bayesian analysis, that might make an excellent vignette. Feel free to share.

**Comment by higgi13425** [comment]
On a less-related note, if you or colleagues would be interested, the R/Medicine virtual meeting might be a worthwile and inexpensive one - to register - https://events.linuxfoundation.org/r-medicine/, and if interested, abstracts are due April 12.
