### ISSUE TITLE
Error in the help documentation for cytomegalovirus

### ISSUE THREAD

**Issue by rosemm** [higgi13425/medicaldata#6]
First, thank you for this wonderful resource! I love having this package available for teaching R. 

I noticed a few of the variables are incorrectly described in the help documentation for cytomegalovirus. In particular, the levels are swapped relative to what is described in the code book and what is presented in the published paper. 

- `sex` should be 0 (female) - 1(male)
- `race ` should be 0 (african-american) - 1 (white)
- `diagnosis.type` should be 0 (lymphoid) - 1 (myeloid)

**Comment by higgi13425** [comment]
Thanks, Rose. I am glad that this package is helpful. The cytomegalovirus codebook was one created by the TSHS folks (and I just borrowed), so I will let them know. They may prefer to correct it themselves in the original PDF, which I just reused for the documentation. If not, I can create a corrected PDF codebook.

**Comment by higgi13425** [comment]
Thanks, Rose. I am glad that the package is helpful. Great catch. Now fixed. Will push up to dev version of Github later today.

**Comment by higgi13425** [comment]
Should be up on dev version. I am hoping to get to 30 datasets before the next update to CRAN this summer.

**Comment by higgi13425** [comment]
Let me know if you have suggestions for improvement, or adding datasets. thanks, Peter

**Comment by rosemm** [comment]
Awesome! Thanks so much for the fast response.
