### ISSUE TITLE
Description not matching the variable in 'strep_tb' dataset

### ISSUE THREAD

**Issue by jromanowska** [higgi13425/medicaldata#7]
The variable `baseline_temp` is described [on the webpage](https://higgi13425.github.io/medicaldata/reference/strep_tb.html) as categorical with 4 categories: 1_afebrile, 2_<99F/<37.2C, 3_99-99.9F/37.2-37.75C, 4_100F+/37.7C+. However, in the dataset, the values are different:

```
levels(strep_tb$baseline_temp)
# [1] "1_98-98.9F"   "2_99-99.9F"   "3_100-100.9F" "4_100F+"     
janitor::tabyl(strep_tb, baseline_temp)
# baseline_temp  n    percent
#  1_98-98.9F    7  0.06542056
#   2_99-99.9F  25  0.23364486
# 3_100-100.9F  32  0.29906542
#    4_100F+    43  0.40186916
```

There are two problems here:
+ the description does not match the data,
+ level `4_100F+` in the data should be `4_101F+`, because the previous level ranges from 100 to 100.9

**Comment by higgi13425** [comment]
Great catch - now fixed, as per original article, and pushed to Github (in the dev version).
Will try to update to CRAN before Sept 1
